name: CI
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode Version
        run: sudo xcode-select -s '/Applications/Xcode_13.2.1.app/Contents/Developer'

      - name: Build
        run: |
          xcodebuild -sdk iphonesimulator -configuration Debug build
